name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Windows Executable
        run: cargo build --release

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: nevil-windows
          path: target/release/nevil.exe

  release:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download the built artifact
        uses: actions/download-artifact@v4
        with:
          name: nevil-windows
          path: .

      - name: Upload Executables to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: nevil.exe
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.RELEASE_TOKEN }}
